version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  app:
    build: .
    container_name: app
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn shoeshop_project.wsgi:application --blind 0.0.0.0:8000
    volumes:
      - ./shoeshop_project:/app
#      - static_volume:/app/static
#      - ./media:/app/media
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  celery:
    build: .
    image: celery:4.0
    container_name: celery
    restart: unless-stopped
    command: celery -A config worker -l INFO
    volumes:
      - ./shoeshop_project:/app
    depends_on:
      - app
      - redis
      - postgres

  flower:
    build: .
    image: mher/flower:2.0
    container_name: flower
    restart: unless-stopped
    command: celery -A config flower
    volumes:
      - ./shoeshop_project:/app
    depends_on:
      - redis
    ports:
      - '5555:5555'

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  stripe:
    image: stripe/stripe-cli:v1.19.1
    container_name: stripe
#    restart: unless-stopped
#    environment:
#      STRIPE_PUBLIC_KEY: 'pk_test_51NtBRsEHgFzglP9yWCayky7DXIohqd82LZaU7kH9P8VtBYhftLhSr7Se2WDVPcdiXtd8oEWcqy0K0hHaTM52oeqD009R6bWUBK'
#      STRIPE_SECRET_KEY: 'sk_test_51NtBRsEHgFzglP9yIL1zTu15lN9oVvsOdcVVRLhGX6ASt0Dg4lsTCCq3LAWcDPHYMXflH68kXPpvQkyUrM5Cogvj0002CBOu7Z'
#      STRIPE_WEBHOOK_SECRET: 'whsec_6b93d183453a6827a2fe99fa67b951d1a33aef6183395e67062d15849155e590'
    entrypoint: stripe
    command: listen --api-key ${STRIPE_SECRET_KEY} --forward-to app:8000/webhooks/stripe/
    env_file:
      - .env
    depends_on:
      - app
      - postgres

    #  nginx:
    #    image: nginx:latest
    #    volumes:
    #      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    #      - static_volume:/static
    #    ports:
    #      - '80:80'
    #    depends_on:
    #      - django

volumes:
  postgres:
#  static_volume:
