version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
#    environment:
#      POSTGRES_USER: eugene
#      POSTGRES_PASSWORD: 1111
#      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  django:
      build: .
      container_name: shoe_shop
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./shoeshop_project:/app
      ports:
        - '8000:8000'
      depends_on:
        - postgres
#      environment:
#        DEBUG: False
#        DB_NAME: postgres
#        DB_USER: eugene
#        DB_PASSWORD: 1111
volumes:
  postgres:
