version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  app:
    build: .
    container_name: app
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn shoeshop_project.wsgi:application --blind 0.0.0.0:8000
    volumes:
      - ./shoeshop_project:/app
#      - static_volume:/app/static
#      - ./media:/app/media
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  celery:
    build: .
    image: celery:4.0
    container_name: celery
    restart: unless-stopped
    command: celery -A config worker -l INFO
    volumes:
      - ./shoeshop_project:/app
    depends_on:
      - app
      - redis

  flower:
    build: .
    image: mher/flower:2.0
    container_name: flower
    restart: unless-stopped
    command: celery -A config flower
    volumes:
      - ./shoeshop_project:/app
    depends_on:
      - redis
    ports:
      - '5555:5555'

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

    #  nginx:
    #    image: nginx:latest
    #    volumes:
    #      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    #      - static_volume:/static
    #    ports:
    #      - '80:80'
    #    depends_on:
    #      - django

volumes:
  postgres:
#  static_volume:
