version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  app:
    build: .
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn shoeshop_project.wsgi:application --blind 0.0.0.0:8000
    volumes:
      - ./shoeshop_project:/app
#      - static_volume:/app/static
#      - ./media:/app/media
    ports:
      - '8000:8000'
    depends_on:
      - postgres
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf
#      - static_volume:/static
#    ports:
#      - '80:80'
#    depends_on:
#      - django

  celery:
    build: .
    container_name: celery
    command: celery -A config worker -l INFO
    volumes:
      - ./shoeshop_project:/app
    depends_on:
      - app
      - redis

  flower:
    build: .
    container_name: flower
    command: celery -A config flower
    volumes:
      - ./shoeshop_project:/app
    depends_on:
      - redis
    ports:
      - '5555:5555'

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  postgres:
#  static_volume:
