# Generated by Django 4.2.5 on 2024-02-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_productimage_options_alter_review_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
