# Generated by Django 4.2.5 on 2024-02-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_review_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_visits',
        ),
    ]
