# Generated by Django 4.2.5 on 2024-02-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_product_num_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchases_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
