# Generated by Django 4.2.5 on 2024-02-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_product_purchases_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
