# Generated by Django 4.2.5 on 2024-02-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_product_actual_price_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
