# Generated by Django 4.2.5 on 2024-02-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='ordered_datetime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_date',
            new_name='start_datetime',
        ),
    ]
